
const bannerStyles = {
  section: {
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
    pt: ["72px", null, null, null, "96px","96px"],
    pb: ["72px", null, null, null, "96px","96px"],
  },
  container: {
    mx:"10%",
    flexDirection: "column",
    position: "relative",
    justifyContent:"center",
  },
  flex: {
    flexWrap: "wrap",
    gap: 0,
  },
  content: {
    flexDirection: "column",
    textAlign: ["center", "center", "left", "left", "left"],
    flex: ["0 0 100%", null, null, null, "0 0 50%", "0 0 40%"],
    h2: {
      color: "#02073E",
      letterSpacing: "-1px",
      fontSize: ["36px", null, "36px", null, "48px", "48px"],
      fontFamily: "Poppins",
      lineHeight: 1.45,
      maxWidth: "546px",
      mb: "8px",
      // mx: ["0", null, null, "auto"],
    },
    h4: {
      fontSize: ["16px", null, "16px"],
      lineHeight: [2, null, 2.62],
      color: "#02073E",
      maxWidth: "486px",
      fontFamily: "Poppins",
    },
    h3: {
      fontSize: ["8px", null, "16px"],
      marginTop: 10,
      lineHeight: [2, null, 2.62],
      color: "#02073E",
      maxWidth: "486px",
      fontFamily: "Poppins",
    },
    p: {
      fontSize: ["8px", null, "16px"],
      marginTop: 10,
      lineHeight: [2, null, 2.62],
      color: "#d95f76",
      maxWidth: "486px",
      fontStyle: "italic",
      fontFamily: "Poppins",
    },
    form: {
      display: "flex",
      flexWrap: "wrap",
      justifyContent: [null, null, null, "center", "flex-start"],
      mt: "24px",
      mb: ["16px", "32px"],
      input: {
        width: ["100%", "216px", "346px", null, "300px", null, "332px"],
        border: "1px solid #E9EDF5",
        borderRadius: "8px",
        mr: ["0", "16px"],
        mb: ["8px", "0"],
        height: ["48px", null, null, null, null, "60px", "60px"],
        fontSize: "16px",
        fontFamily: "Poppins",
        color: "rgba(2,7,62,.4)",
        backgroundColor: "#ffffff",
        px: "24px",
        boxShadow: "none !important",
        outline: "none !important",
        "&::placeholder": {
          color: "rgba(2,7,62,.4)",
        },
        "&:focus": {
          border: "primary",
        },
      },
      button: {
        fontSize: "16px",
        fontFamily: "Poppins",
        color: "#ffff",
        fontWeight: 700,
        borderRadius: "8px",
        height: ["48px", null, null, null, null, "60px", "60px"],
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        textAlign: "center",
        padding: "0 32px",
        WebkitAppearance: "none",
        appearance: "none",
        outline: "none",
        cursor: "pointer",
        mx: ["auto", 0],
        transition: "all 500ms ease",
        "&:hover": {
          backgroundColor: "secondary",
        },
      },
    },
  },
  images: {
    flex: ["0 0 100%", null, null, null, "0 0 50%", "0 0 60%"],
    position: "relative",
    left: ["auto", null, null, null, "48px", "96px"],
    mt: ["24px", null, "32px", null, "0"],
  },
  clients: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    justifyContent: ["center", null, null, "center", "flex-start"],
    span: {
      color: "#566272",
      opacity: 0.6,
      flex: ["0 0 100%", "1 1 100%", "0 0 auto"],
      mb: ["8px", null, "0"],
      textAlign: ["center", null, "left"],
    },
    a: {
      display: "flex",
      alignItems: "center",
      ml: ["8px", "16px", null, "16px", "0px", null, "16px"],
      img: {
        display: "block",
      },
    },
  },
  signupButton: {
    borderRadius: "32px",
    backgroundColor: "#D7354A",
    px: "32px",
    py: "8px",
    justifyContent: "center",
    alignItems: "center",
    "&:hover": {
      backgroundColor: "#d42a40",
    },
    cursor: "pointer",
  },
  signupButtonText: {
    fontFamily: "Poppins",
    fontWeight: "medium",
    fontSize: "16px",
    color: "white",
  },
  gettingStartedFlex: {
    justifyContent:["center","center","left","left","left","left"]
  },
  gettingStartedButton: {
    backgroundColor: "#D7354A",
    color: "white",
    py: "24px",
    px: "48px",
    mb:"16px",
    width: "248px",
    borderRadius: "32px",
    cursor: "pointer",
    fontFamily: "Poppins",
    fontWeight: "bold",
    fontSize: "md",
    "&:hover": {
      backgroundColor: "#d42a40",
    },
  }
};

export default bannerStyles;