
const productsCardStyles = {
  container: {
    flexDirection: "column",
    // p: "8px",
    // py: "16px",
    backgroundColor: "white",
    borderRadius: "0px",
    boxShadow: "0 0 4px 1px rgba(0, 0, 0, 0.1)",
    mx: "8px",
    width: "200px",
    // width: ["100%", "100%", "350px", "350px", "448px", "448px"],
    // minWidth: "330px",
    my: "8px",
    cursor: "pointer",
    position: "relative",
  },
  imageMaster: {
    backgroundColor: "white",
  },
  imageContainer: {
    // mx: "8px",
    backgroundColor: "white",
  },
  image: {
    height: "200px",
    width: "200px",
    borderRadius: "8px",
  },
  categoryDetailsContainer: {
    mt: "-20px",
    justifyContent: "center",
    alignItems: "center",
  },
  detailsContainer: {
    backgroundColor: "white",
    flexDirection: "column",
    my: "6px",
    justifyContent: "space-between",
    textAlign: "center",
  },
  buttonText: {
    width: "100%",
    height: "100%",
    backgroundColor: "transparent",
    borderWidth: "0px",
    color: "white",
    fontWeight: "medium",
    fontFamily: "Poppins",
    fontSize: "16px",
    cursor: "pointer",
    textAlign: "center",
  },
  button: {
    backgroundColor: "#D7354A",
    borderRadius: "24px",
    borderColor: "#D7354A",
    py: "4px",
    width: "148px",
    alignItems: "center",
    justifyContent: "center",
  },
  content: {
    flexDirection: "column",
    px: "4px",
  },
  buttonContainer: {
    justifyContent: "center",
    width: "100%",
  },
  product: {
    fontFamily: "Poppins",
    fontWeight: "medium",
    fontSize: "12px",
    fontWeight: "bold",
    color: "#000",
  },
  category: {
    fontFamily: "Poppins",
    fontWeight: "medium",
    fontSize: "10px",
    color: "white",
    textAlign: "center",
  },
  buynow: {},
  categoryContent: {
    backgroundColor: "#D7354A",
    height: "30px",
    justifyContent: "center",
    alignItems: "center",
    px: "4px",
    borderRadius: "8px",
  },
};

export default productsCardStyles;