const userSummaryStyles = {
  container: {
    display: "flex",
    flexDirection: "column",
    mt: "16px",
  },
  buttonContainer: {
    width: "300px",
    mx:"auto",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  summaryView: {
    width: "300px",
    mx:"auto",
    flexDirection: "row",
    justifyContent: "space-between",
    mt: "8px",
  },
  button: {
    backgroundColor: "#D7354A",
    // mr:"50px",
    borderRadius: "4px",
    borderColor: "#D7354A",
    py: "2px",
    width: "120px",
    height:"40px",
    borderWidth: 1,
  },
  summaryText: {
    display: ["none", "none", "inline", "inline", "inline", "inline"],
    fontWeight: "bold",
    fontFamily: "Open Sans",
    fontSize: "14px",
  },
  buttonText: {
    ':hover': {backgroundColor:"#D7354A", 
    boxShadow: "none", outline:"none"},
    ':focus': {backgroundColor:"#D7354A", 
    boxShadow: "none", outline:"none"},
    width: "100%",
    height: "100%",
    backgroundColor: "transparent",
    borderWidth: "0px",
    color: "white",
    fontWeight: "bold",
    fontFamily: "Open Sans",
    fontSize: "12px",
    cursor: "pointer",
  },
  button1: {
    // ml:"50px",
    backgroundColor: "white",
    borderRadius: "4px",
    borderColor: "#D7354A",
    py: "2px",
    borderWidth: 1,
    width: "120px",
    height:"40px",
  },
  buttonText1: {
    ':hover': {backgroundColor:"white", 
    boxShadow: "none", outline:"none"},
    ':focus': {backgroundColor:"white", 
    boxShadow: "none", outline:"none"},
    width: "100%",
    height: "100%",
    backgroundColor: "transparent",
    borderWidth: "0px",
    color: "#D7354A",
    fontWeight: "bold",
    fontFamily: "Open Sans",
    fontSize: "12px",
    cursor: "pointer",
  },
  summaryView1: {
    flexDirection: "row",
    justifyContent: "space-between",
    mx: "10%",
    mt: "8px",
  },
  summaryText1: {
    display: ["none", "none", "inline", "inline", "inline", "inline"],
    fontWeight: "medium",
    fontFamily: "Open Sans",
    fontSize: "14px",
  },
};

export default userSummaryStyles;
